services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/rosconjp24
    ports:
      - 7447:7447
    working_dir: /root/rosconjp24
    stdin_open: true
    tty: true